### ISSUE TITLE
Failed to verify bitcode issue

### ISSUE THREAD

**Issue by damirstuhec** [yannickl/DynamicColor#14]
I get the following error message while trying to do an Ad-Hoc export of project that uses DynamicColor framework:

```
Failed to verify bitcode in DynamicColor.framework/DynamicColor:

description = "Failed to verify bitcode in DynamicColor.framework/DynamicColor:\nerror: Cannot extract bundle
level = ERROR;
type = "malformed-payload";
```

It happens in `Compile Bitcode` expert step.

**Comment by yannickl** [comment]
Hi Damir,

Which version are you using? Do you work with Cocoapods?

**Comment by damirstuhec** [comment]
Latest version, Xcode 8, Swift 3, Carthage.

**Comment by yannickl** [comment]
Ok, thank you, I'll try to take a look tonight. 👍

**Comment by damirstuhec** [comment]
Thanks!

**Comment by yannickl** [comment]
I've tested it with a sample project and it works fine for me. When the error occurred? During the archive or in debug mode?

**Comment by damirstuhec** [comment]
During archive for Ad-Hoc export.

Side note: I have no other dependency in the project.

**Comment by yannickl** [comment]
I've created an empty project and I only import the DynamicColor lib using carthage (and I put some code to use the lib) then I Archive in Ad-hoc with the bitcode enabled and it works fine.

Does it work with an empty project in your side? Or have you an example project?

**Comment by damirstuhec** [comment]
@yannickl Seems to work now all of a suden. 🙈 Thank you anyway!
