### ISSUE TITLE
Cautionary Tale: hue ranges have changed

### ISSUE THREAD

**Issue by SuperWomble** [yannickl/DynamicColor#17]
This is more of a lighthouse for anyone who crashes on the rocks of `adjustedHue` as I did!  

The range has been changed from [0, 1] to [-360, 360].  So if you don't see any changes when shift your color's hue by 0.1, you'll know why; the color has changed, but by very little!

Oh well, next time I'll read the Change Log a bit more carefully. :p

Awesome project, BTW. Thanks a bunch for all your work.

**Comment by yannickl** [comment]
Hi,

Yes I've done a lot of refactoring while the migration to Swift3. I should, may be, highlight the change in the README but I'm afraid it makes reading more difficult...

Thank you for the feedback! 👍
