### ISSUE TITLE
Using pods (v 3.1.0) doesn't download the version with swift 3.0

### ISSUE THREAD

**Issue by mihaigabriel1992** [yannickl/DynamicColor#18]
After installing the v3.1.0 in my project with Xcode 3.0 it returns an error that some code is not swift 3.0. I looked over the example and it's a different code from the pod one. 

Any suggestion?

**Comment by yannickl** [comment]
Which version of Cocoapods are you using? And have you tried to update your Cocoapods cache?

```bash
pod repo update
```

**Comment by mihaigabriel1992** [comment]
I've done both of that. The problem is for Apple TV, not iOS.
