### ISSUE TITLE
Gradient colors

### ISSUE THREAD

**Issue by nubbel** [yannickl/DynamicColor#2]
It would be nice to have a method that generates color on a gradient between two colors.
API might look like that:

```swift
red.gradientTo(green).colorAt(0.5) // yellow-ish
```

**Comment by Master00** [comment]
What language is this?

**Comment by nubbel** [comment]
Hmm?

**Comment by yannickl** [comment]
I wonder if this feature should be available in this library or if an another library could not be more relevant?

I need to study the issue (if another people want participate it could be nice).

Moreover I don't think the fluent API is necessary in this case, I prefer something like that:

```swift
red.gradientTo(green, at: 0.5)
```

**Comment by SuperWomble** [comment]
My two cents: gradients are a drawing operation, not a color operation as such. I think gradients are best handled in other libraries entirely. IMO, this (excellent) project should just focus on color.

**Comment by nubbel** [comment]
This issue is not about drawing gradients (we have `CAGradientLayer` for that), but about picking a color that lies on a point of a gradient from one color to another which has nothing to do with a drawing operation IMHO.

**Comment by yannickl** [comment]
Indeed I don't think that "drawing" gradients is pertinent for the library. But building a gradient color array and / or picking a color from it can be useful.

For the next version of the library I've started to work [work on](https://github.com/yannickl/DynamicColor/blob/master/Sources/Array.swift) but it needs to be involved and refined the API design.
