### ISSUE TITLE
Implementing a `isContrasting` method

### ISSUE THREAD

**Issue by yannickl** [yannickl/DynamicColor#22]
A `isContrasting` method could be useful for accessibility. We should follow the [WCAG 2.0](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast) recommendation.

Related to the #21.

**Comment by Onejjy** [comment]
I think we can close this one ;)

**Comment by yannickl** [comment]
Yes, thank you!
