### ISSUE TITLE
Implementing SwiftLint

### ISSUE THREAD

**Issue by Onejjy** [yannickl/DynamicColor#28]
Hello, 

I think that could be a great thing to add [SwiftLint](https://github.com/realm/SwiftLint) to this project. It will force us to maintain clean code. It also helps to avoid some mistakes. 

And there is a little trick: if we use ’swift lint autocorrect’, it fixes automatically the majority of the code formatting issues! What do you think about it? 

If it’s OK to you, I’ll make a PR with the SwiftLint implantation.

**Comment by yannickl** [comment]
Hey Julien,

Yes I approve totally! Anything that can improve the code quality is good to take!

However I'm not sure about the autocorrect option because, as developer, I think it is important to see our mistakes. :)

**Comment by yannickl** [comment]
I'm closing it because of #29.
