### ISSUE TITLE
Swift 2.3 version?

### ISSUE THREAD

**Issue by Domsware** [yannickl/DynamicColor#30]
How to get Swift2.3 version?

**Comment by yannickl** [comment]
The [v2.4.0](https://github.com/yannickl/DynamicColor/tree/2.4.0) should work with Swift2.3.

**Comment by Domsware** [comment]
OK, thank you!

**Comment by Domsware** [comment]
Argghh ! It does not work!

## Cartfile
github "yannickl/DynamicColor" "2.4.0"

## Log
```
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /MY-PROJECT/Carthage/Checkouts/DynamicColor/Example/DynamicColorExample.xcodeproj -scheme DynamicColor -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by yannickl** [comment]
Which Xcode version are you using?

I've not tried with Carthage but I tried the example with Xcode 8.2.1 and it works but I have to set the `Use Legacy Swift Language Version` to `YES`.

Before to push anything I would you test it by modifying the framework settings.

**Comment by Domsware** [comment]
Xcode 8.1

Test is done for a projet using Swift 2.3 and having few others frameworks added using Carthage.

If my memory is correct I already have this kind of issue some months ago on for another GitHub project; problem has then been solved by adding `Use Legacy Swift Language Version` to `YES` on library side.

**Comment by Domsware** [comment]
Sorry but I don't know how to achieve what you asked me to do: test it by modifying the framework settings.

Do I have to modify framework source code on Carthage checkout directory?
And then build to test if it's ok ? `

**Comment by Domsware** [comment]
OK. I figured how to achieve this tes by using `carthage build`command.

Once `Use Legacy Swift Language Version` is set to `YES`, carthage build worked just fine.

**Comment by yannickl** [comment]
Ah great, good news! May be I should create a `swift2.3` branch with the settings already configured.

But `swift2.3` is almost dead, so I don't think it is  pertinent.

**Comment by Domsware** [comment]
I think you're right. If someone have such problem then this issue is enough to bring the answer.
