### ISSUE TITLE
Alpha value 

### ISSUE THREAD

**Issue by alexsanderkhitev** [yannickl/DynamicColor#31]
Hi, I tried to install the alpha value through this library, but the results did not get, tell me how to fix it?

My example 
` UIColor.white.adjustedAlpha(amount: 0.75)`

**Comment by yannickl** [comment]
Hi,

The `adjustedAlpha` the alpha channel and returns the new color. To get the alpha component, just use the `alphaComponent` property.

**Comment by alexsanderkhitev** [comment]
@yannickl  Thanks!
