### ISSUE TITLE
hex should support the alpha channel

### ISSUE THREAD

**Issue by hyouuu** [yannickl/DynamicColor#34]
Thanks for the library! I saw that currently alpha is always set to FF, which limits its usefulness. Could you update so that alpha value could also be supported? e.g. when the hex has 8 digits, use the last 2 as alpha, if the hex has 6 digits, default to FF

**Comment by yannickl** [comment]
Hi @hyouuu,

I don't have enough time for the moment, but this is a good idea. I'll update the lib in the next weeks,  or if you have time you are welcomed to contribute.

Best

**Comment by yannickl** [comment]
The last version now support the alpha channel with the hex strings.
