### ISSUE TITLE
Minor issue: proposed fix for improved Swift compilation times

### ISSUE THREAD

**Issue by SuperWomble** [yannickl/DynamicColor#39]
File: `DynamicColor.swift`

Note: this issue is not a developer fault: it's just a limitation of the Swift compiler at this stage. Using Xcode  9.2 beta 1 (9C32c)

**Problem:**

In the nested function `roundToHex(_ x: CGFloat)`, the following line takes over 200ms to compile on a MBP:

`return UInt32(round(1000 * x) / 1000 * 255)`

**Proposed Fix**

Adding the type saves Xcode the job of thinking:

```
let rounded: CGFloat = round(1000 * x)
return UInt32(rounded / 1000 * 255)
```

Cheers, and thanks for all your work on this project.

**Comment by yannickl** [comment]
Hi @SuperWomble,

Thank you for the tips. The last version has been updated with you improvements. 👍
