### ISSUE TITLE
Could you downgrade the iOS version of framework target from iOS 8.3 to iOS 8.0?

### ISSUE THREAD

**Issue by lexrus** [yannickl/DynamicColor#4]
My project is compatible to iOS 8.0. After building the framework with Carthage and embed into my project, Xcode told me that this framework was set to work with iOS 8.3 above.
I believe this could be fixed by downgrading the Deployment Target of the framework.
<img width="550" alt="screen shot 2015-07-29 at 5 27 48 pm" src="https://cloud.githubusercontent.com/assets/219689/8954318/458fa790-3617-11e5-980b-84a5c5e127b8.png">

**Comment by yannickl** [comment]
It's my mistake, I put the target to iOS 8.0. It should works now.

**Comment by lexrus** [comment]
It works. Thank you.
