### ISSUE TITLE
Fatal error: Not enough bits to represent the passed value

### ISSUE THREAD

**Issue by leogiertz** [yannickl/DynamicColor#47]
**Describe the bug**
We got a crash on an iPhone 5C running iOS 10.3.3 and it's triggered by this line:

```
UIColor(hex: 0xffffff80, useAlpha: true)
```

The crash happens on line 87 in DynamicColor.swift since Int is the same size as Int32 on 32 bit platforms.

**To Reproduce**
1. Add the line above to a project
2. Run it on an iPhone 5 using iOS 10.x in a simulator
3. See crash

**Expected behavior**
To not crash. :)

**Smartphone (please complete the following information):**
 - Device: 32 bit devices, i.e. iPhone 5C
 - OS: 10.3

**Additional context**

**Comment by yannickl** [comment]
Thank you for the report.

I can't reproduce it on the simulator (iPhone 5, 10.0 and 10.3.1). Moreover the signature defines the hex as a `UInt32` so it should works in 32bit environments.

Which Xcode version do you use? Is it the last `DynamicColor` version?

**Comment by leogiertz** [comment]
We're using the latest version of DynamicColor available on Cocoapods (4.0.2).

If you check the current master it probably was fixed here: https://github.com/yannickl/DynamicColor/commit/8b3e06c00ff563713ce16ad91e392e2641eb360f

Would be great with a new release. 🌟

**Comment by yannickl** [comment]
I forgot to release the fixes/updates for a while... You're right. I've just bumped the version.

Keep me in touch please.

**Comment by leogiertz** [comment]
With 4.0.3 I can no longer reproduce the crash. Thanks for releasing it and thanks for maintaining this project! 🎈
