### ISSUE TITLE
Manipulate alpha component of color

### ISSUE THREAD

**Issue by Nailer** [yannickl/DynamicColor#8]
How about a convenience function for manipulating the alpha component of a color? It seems like you can manipulate just about every other aspect of the color, except that.

If there's already an easy way to do this that I have missed?

**Comment by yannickl** [comment]
You would like a kind of `adjustedAlphaColor` method or something more specific?

For the moment there is nothing to manipulate the alpha component, only getters.

**Comment by Nailer** [comment]
That is indeed what I was looking for :)

**Comment by yannickl** [comment]
I just added the `adjustedAlphaColor` method. This method is not a setter for the alpha component but it adds the given amount to the alpha.
